#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PShop.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PSHOP")]
	public partial class PSHOPEntityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLoginTbl(LoginTbl instance);
    partial void UpdateLoginTbl(LoginTbl instance);
    partial void DeleteLoginTbl(LoginTbl instance);
    partial void InsertMobileTbl(MobileTbl instance);
    partial void UpdateMobileTbl(MobileTbl instance);
    partial void DeleteMobileTbl(MobileTbl instance);
    partial void InsertMobileDetailTbl(MobileDetailTbl instance);
    partial void UpdateMobileDetailTbl(MobileDetailTbl instance);
    partial void DeleteMobileDetailTbl(MobileDetailTbl instance);
    partial void InsertOrderTbl(OrderTbl instance);
    partial void UpdateOrderTbl(OrderTbl instance);
    partial void DeleteOrderTbl(OrderTbl instance);
    partial void InsertCartTbl(CartTbl instance);
    partial void UpdateCartTbl(CartTbl instance);
    partial void DeleteCartTbl(CartTbl instance);
    #endregion
		
		public PSHOPEntityDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PSHOPConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PSHOPEntityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PSHOPEntityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PSHOPEntityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PSHOPEntityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LoginTbl> LoginTbls
		{
			get
			{
				return this.GetTable<LoginTbl>();
			}
		}
		
		public System.Data.Linq.Table<MobileTbl> MobileTbls
		{
			get
			{
				return this.GetTable<MobileTbl>();
			}
		}
		
		public System.Data.Linq.Table<MobileDetailTbl> MobileDetailTbls
		{
			get
			{
				return this.GetTable<MobileDetailTbl>();
			}
		}
		
		public System.Data.Linq.Table<OrderTbl> OrderTbls
		{
			get
			{
				return this.GetTable<OrderTbl>();
			}
		}
		
		public System.Data.Linq.Table<CartTbl> CartTbls
		{
			get
			{
				return this.GetTable<CartTbl>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoginTbl")]
	public partial class LoginTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserId;
		
		private string _LoginPassword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnLoginPasswordChanging(string value);
    partial void OnLoginPasswordChanged();
    #endregion
		
		public LoginTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginPassword", DbType="VarChar(50)")]
		public string LoginPassword
		{
			get
			{
				return this._LoginPassword;
			}
			set
			{
				if ((this._LoginPassword != value))
				{
					this.OnLoginPasswordChanging(value);
					this.SendPropertyChanging();
					this._LoginPassword = value;
					this.SendPropertyChanged("LoginPassword");
					this.OnLoginPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MobileTbl")]
	public partial class MobileTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MobileName;
		
		private string _BrandName;
		
		private int _MobileInfoId;
		
		private double _Price;
		
		private double _Discount;
		
		private int _Ram;
		
		private int _Rom;
		
		private double _Size;
		
		private string _SKU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMobileNameChanging(string value);
    partial void OnMobileNameChanged();
    partial void OnBrandNameChanging(string value);
    partial void OnBrandNameChanged();
    partial void OnMobileInfoIdChanging(int value);
    partial void OnMobileInfoIdChanged();
    partial void OnPriceChanging(double value);
    partial void OnPriceChanged();
    partial void OnDiscountChanging(double value);
    partial void OnDiscountChanged();
    partial void OnRamChanging(int value);
    partial void OnRamChanged();
    partial void OnRomChanging(int value);
    partial void OnRomChanged();
    partial void OnSizeChanging(double value);
    partial void OnSizeChanged();
    partial void OnSKUChanging(string value);
    partial void OnSKUChanged();
    #endregion
		
		public MobileTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MobileName
		{
			get
			{
				return this._MobileName;
			}
			set
			{
				if ((this._MobileName != value))
				{
					this.OnMobileNameChanging(value);
					this.SendPropertyChanging();
					this._MobileName = value;
					this.SendPropertyChanged("MobileName");
					this.OnMobileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string BrandName
		{
			get
			{
				return this._BrandName;
			}
			set
			{
				if ((this._BrandName != value))
				{
					this.OnBrandNameChanging(value);
					this.SendPropertyChanging();
					this._BrandName = value;
					this.SendPropertyChanged("BrandName");
					this.OnBrandNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileInfoId", DbType="Int NOT NULL")]
		public int MobileInfoId
		{
			get
			{
				return this._MobileInfoId;
			}
			set
			{
				if ((this._MobileInfoId != value))
				{
					this.OnMobileInfoIdChanging(value);
					this.SendPropertyChanging();
					this._MobileInfoId = value;
					this.SendPropertyChanged("MobileInfoId");
					this.OnMobileInfoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float NOT NULL")]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="Float NOT NULL")]
		public double Discount
		{
			get
			{
				return this._Discount;
			}
			set
			{
				if ((this._Discount != value))
				{
					this.OnDiscountChanging(value);
					this.SendPropertyChanging();
					this._Discount = value;
					this.SendPropertyChanged("Discount");
					this.OnDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ram", DbType="Int NOT NULL")]
		public int Ram
		{
			get
			{
				return this._Ram;
			}
			set
			{
				if ((this._Ram != value))
				{
					this.OnRamChanging(value);
					this.SendPropertyChanging();
					this._Ram = value;
					this.SendPropertyChanged("Ram");
					this.OnRamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rom", DbType="Int NOT NULL")]
		public int Rom
		{
			get
			{
				return this._Rom;
			}
			set
			{
				if ((this._Rom != value))
				{
					this.OnRomChanging(value);
					this.SendPropertyChanging();
					this._Rom = value;
					this.SendPropertyChanged("Rom");
					this.OnRomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Float NOT NULL")]
		public double Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", DbType="NVarChar(20)")]
		public string SKU
		{
			get
			{
				return this._SKU;
			}
			set
			{
				if ((this._SKU != value))
				{
					this.OnSKUChanging(value);
					this.SendPropertyChanging();
					this._SKU = value;
					this.SendPropertyChanged("SKU");
					this.OnSKUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MobileDetailTbl")]
	public partial class MobileDetailTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MobileName;
		
		private string _BrandName;
		
		private int _MobileInfoId;
		
		private double _Price;
		
		private double _Discount;
		
		private int _Ram;
		
		private int _Rom;
		
		private double _Size;
		
		private string _SKU;
		
		private string _ProductType;
		
		private string _Model;
		
		private string _Display;
		
		private string _Resolution;
		
		private string _DisplayType;
		
		private string _DisplayProtection;
		
		private string _OS;
		
		private string _Chipset;
		
		private string _CPU;
		
		private string _GPU;
		
		private string _MemoryCardSlot;
		
		private string _Camera;
		
		private string _Features;
		
		private string _Video;
		
		private string _SelfieCamera;
		
		private string _WLAN;
		
		private string _Bluetooth;
		
		private string _GPS;
		
		private string _Radio;
		
		private string _USB;
		
		private string _Sensors;
		
		private string _BatteryType;
		
		private string _BatteryCharging;
		
		private string _Jack;
		
		private string _SIM;
		
		private string _NetworkTechnology;
		
		private string _Dimensions;
		
		private string _WeightGm;
		
		private int _Quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMobileNameChanging(string value);
    partial void OnMobileNameChanged();
    partial void OnBrandNameChanging(string value);
    partial void OnBrandNameChanged();
    partial void OnMobileInfoIdChanging(int value);
    partial void OnMobileInfoIdChanged();
    partial void OnPriceChanging(double value);
    partial void OnPriceChanged();
    partial void OnDiscountChanging(double value);
    partial void OnDiscountChanged();
    partial void OnRamChanging(int value);
    partial void OnRamChanged();
    partial void OnRomChanging(int value);
    partial void OnRomChanged();
    partial void OnSizeChanging(double value);
    partial void OnSizeChanged();
    partial void OnSKUChanging(string value);
    partial void OnSKUChanged();
    partial void OnProductTypeChanging(string value);
    partial void OnProductTypeChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnDisplayChanging(string value);
    partial void OnDisplayChanged();
    partial void OnResolutionChanging(string value);
    partial void OnResolutionChanged();
    partial void OnDisplayTypeChanging(string value);
    partial void OnDisplayTypeChanged();
    partial void OnDisplayProtectionChanging(string value);
    partial void OnDisplayProtectionChanged();
    partial void OnOSChanging(string value);
    partial void OnOSChanged();
    partial void OnChipsetChanging(string value);
    partial void OnChipsetChanged();
    partial void OnCPUChanging(string value);
    partial void OnCPUChanged();
    partial void OnGPUChanging(string value);
    partial void OnGPUChanged();
    partial void OnMemoryCardSlotChanging(string value);
    partial void OnMemoryCardSlotChanged();
    partial void OnCameraChanging(string value);
    partial void OnCameraChanged();
    partial void OnFeaturesChanging(string value);
    partial void OnFeaturesChanged();
    partial void OnVideoChanging(string value);
    partial void OnVideoChanged();
    partial void OnSelfieCameraChanging(string value);
    partial void OnSelfieCameraChanged();
    partial void OnWLANChanging(string value);
    partial void OnWLANChanged();
    partial void OnBluetoothChanging(string value);
    partial void OnBluetoothChanged();
    partial void OnGPSChanging(string value);
    partial void OnGPSChanged();
    partial void OnRadioChanging(string value);
    partial void OnRadioChanged();
    partial void OnUSBChanging(string value);
    partial void OnUSBChanged();
    partial void OnSensorsChanging(string value);
    partial void OnSensorsChanged();
    partial void OnBatteryTypeChanging(string value);
    partial void OnBatteryTypeChanged();
    partial void OnBatteryChargingChanging(string value);
    partial void OnBatteryChargingChanged();
    partial void OnJackChanging(string value);
    partial void OnJackChanged();
    partial void OnSIMChanging(string value);
    partial void OnSIMChanged();
    partial void OnNetworkTechnologyChanging(string value);
    partial void OnNetworkTechnologyChanged();
    partial void OnDimensionsChanging(string value);
    partial void OnDimensionsChanged();
    partial void OnWeightGmChanging(string value);
    partial void OnWeightGmChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    #endregion
		
		public MobileDetailTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MobileName
		{
			get
			{
				return this._MobileName;
			}
			set
			{
				if ((this._MobileName != value))
				{
					this.OnMobileNameChanging(value);
					this.SendPropertyChanging();
					this._MobileName = value;
					this.SendPropertyChanged("MobileName");
					this.OnMobileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string BrandName
		{
			get
			{
				return this._BrandName;
			}
			set
			{
				if ((this._BrandName != value))
				{
					this.OnBrandNameChanging(value);
					this.SendPropertyChanging();
					this._BrandName = value;
					this.SendPropertyChanged("BrandName");
					this.OnBrandNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileInfoId", DbType="Int NOT NULL")]
		public int MobileInfoId
		{
			get
			{
				return this._MobileInfoId;
			}
			set
			{
				if ((this._MobileInfoId != value))
				{
					this.OnMobileInfoIdChanging(value);
					this.SendPropertyChanging();
					this._MobileInfoId = value;
					this.SendPropertyChanged("MobileInfoId");
					this.OnMobileInfoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float NOT NULL")]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="Float NOT NULL")]
		public double Discount
		{
			get
			{
				return this._Discount;
			}
			set
			{
				if ((this._Discount != value))
				{
					this.OnDiscountChanging(value);
					this.SendPropertyChanging();
					this._Discount = value;
					this.SendPropertyChanged("Discount");
					this.OnDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ram", DbType="Int NOT NULL")]
		public int Ram
		{
			get
			{
				return this._Ram;
			}
			set
			{
				if ((this._Ram != value))
				{
					this.OnRamChanging(value);
					this.SendPropertyChanging();
					this._Ram = value;
					this.SendPropertyChanged("Ram");
					this.OnRamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rom", DbType="Int NOT NULL")]
		public int Rom
		{
			get
			{
				return this._Rom;
			}
			set
			{
				if ((this._Rom != value))
				{
					this.OnRomChanging(value);
					this.SendPropertyChanging();
					this._Rom = value;
					this.SendPropertyChanged("Rom");
					this.OnRomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Float NOT NULL")]
		public double Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SKU
		{
			get
			{
				return this._SKU;
			}
			set
			{
				if ((this._SKU != value))
				{
					this.OnSKUChanging(value);
					this.SendPropertyChanging();
					this._SKU = value;
					this.SendPropertyChanged("SKU");
					this.OnSKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this.OnProductTypeChanging(value);
					this.SendPropertyChanging();
					this._ProductType = value;
					this.SendPropertyChanged("ProductType");
					this.OnProductTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Display", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Display
		{
			get
			{
				return this._Display;
			}
			set
			{
				if ((this._Display != value))
				{
					this.OnDisplayChanging(value);
					this.SendPropertyChanging();
					this._Display = value;
					this.SendPropertyChanged("Display");
					this.OnDisplayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resolution", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Resolution
		{
			get
			{
				return this._Resolution;
			}
			set
			{
				if ((this._Resolution != value))
				{
					this.OnResolutionChanging(value);
					this.SendPropertyChanging();
					this._Resolution = value;
					this.SendPropertyChanged("Resolution");
					this.OnResolutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DisplayType
		{
			get
			{
				return this._DisplayType;
			}
			set
			{
				if ((this._DisplayType != value))
				{
					this.OnDisplayTypeChanging(value);
					this.SendPropertyChanging();
					this._DisplayType = value;
					this.SendPropertyChanged("DisplayType");
					this.OnDisplayTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayProtection", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DisplayProtection
		{
			get
			{
				return this._DisplayProtection;
			}
			set
			{
				if ((this._DisplayProtection != value))
				{
					this.OnDisplayProtectionChanging(value);
					this.SendPropertyChanging();
					this._DisplayProtection = value;
					this.SendPropertyChanged("DisplayProtection");
					this.OnDisplayProtectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OS", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OS
		{
			get
			{
				return this._OS;
			}
			set
			{
				if ((this._OS != value))
				{
					this.OnOSChanging(value);
					this.SendPropertyChanging();
					this._OS = value;
					this.SendPropertyChanged("OS");
					this.OnOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chipset", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Chipset
		{
			get
			{
				return this._Chipset;
			}
			set
			{
				if ((this._Chipset != value))
				{
					this.OnChipsetChanging(value);
					this.SendPropertyChanging();
					this._Chipset = value;
					this.SendPropertyChanged("Chipset");
					this.OnChipsetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CPU
		{
			get
			{
				return this._CPU;
			}
			set
			{
				if ((this._CPU != value))
				{
					this.OnCPUChanging(value);
					this.SendPropertyChanging();
					this._CPU = value;
					this.SendPropertyChanged("CPU");
					this.OnCPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string GPU
		{
			get
			{
				return this._GPU;
			}
			set
			{
				if ((this._GPU != value))
				{
					this.OnGPUChanging(value);
					this.SendPropertyChanging();
					this._GPU = value;
					this.SendPropertyChanged("GPU");
					this.OnGPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemoryCardSlot", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MemoryCardSlot
		{
			get
			{
				return this._MemoryCardSlot;
			}
			set
			{
				if ((this._MemoryCardSlot != value))
				{
					this.OnMemoryCardSlotChanging(value);
					this.SendPropertyChanging();
					this._MemoryCardSlot = value;
					this.SendPropertyChanged("MemoryCardSlot");
					this.OnMemoryCardSlotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Camera", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Camera
		{
			get
			{
				return this._Camera;
			}
			set
			{
				if ((this._Camera != value))
				{
					this.OnCameraChanging(value);
					this.SendPropertyChanging();
					this._Camera = value;
					this.SendPropertyChanged("Camera");
					this.OnCameraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Features", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Features
		{
			get
			{
				return this._Features;
			}
			set
			{
				if ((this._Features != value))
				{
					this.OnFeaturesChanging(value);
					this.SendPropertyChanging();
					this._Features = value;
					this.SendPropertyChanged("Features");
					this.OnFeaturesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Video", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Video
		{
			get
			{
				return this._Video;
			}
			set
			{
				if ((this._Video != value))
				{
					this.OnVideoChanging(value);
					this.SendPropertyChanging();
					this._Video = value;
					this.SendPropertyChanged("Video");
					this.OnVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelfieCamera", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SelfieCamera
		{
			get
			{
				return this._SelfieCamera;
			}
			set
			{
				if ((this._SelfieCamera != value))
				{
					this.OnSelfieCameraChanging(value);
					this.SendPropertyChanging();
					this._SelfieCamera = value;
					this.SendPropertyChanged("SelfieCamera");
					this.OnSelfieCameraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WLAN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string WLAN
		{
			get
			{
				return this._WLAN;
			}
			set
			{
				if ((this._WLAN != value))
				{
					this.OnWLANChanging(value);
					this.SendPropertyChanging();
					this._WLAN = value;
					this.SendPropertyChanged("WLAN");
					this.OnWLANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bluetooth", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Bluetooth
		{
			get
			{
				return this._Bluetooth;
			}
			set
			{
				if ((this._Bluetooth != value))
				{
					this.OnBluetoothChanging(value);
					this.SendPropertyChanging();
					this._Bluetooth = value;
					this.SendPropertyChanged("Bluetooth");
					this.OnBluetoothChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPS", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string GPS
		{
			get
			{
				return this._GPS;
			}
			set
			{
				if ((this._GPS != value))
				{
					this.OnGPSChanging(value);
					this.SendPropertyChanging();
					this._GPS = value;
					this.SendPropertyChanged("GPS");
					this.OnGPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Radio", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Radio
		{
			get
			{
				return this._Radio;
			}
			set
			{
				if ((this._Radio != value))
				{
					this.OnRadioChanging(value);
					this.SendPropertyChanging();
					this._Radio = value;
					this.SendPropertyChanged("Radio");
					this.OnRadioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string USB
		{
			get
			{
				return this._USB;
			}
			set
			{
				if ((this._USB != value))
				{
					this.OnUSBChanging(value);
					this.SendPropertyChanging();
					this._USB = value;
					this.SendPropertyChanged("USB");
					this.OnUSBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sensors", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Sensors
		{
			get
			{
				return this._Sensors;
			}
			set
			{
				if ((this._Sensors != value))
				{
					this.OnSensorsChanging(value);
					this.SendPropertyChanging();
					this._Sensors = value;
					this.SendPropertyChanged("Sensors");
					this.OnSensorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatteryType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BatteryType
		{
			get
			{
				return this._BatteryType;
			}
			set
			{
				if ((this._BatteryType != value))
				{
					this.OnBatteryTypeChanging(value);
					this.SendPropertyChanging();
					this._BatteryType = value;
					this.SendPropertyChanged("BatteryType");
					this.OnBatteryTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatteryCharging", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BatteryCharging
		{
			get
			{
				return this._BatteryCharging;
			}
			set
			{
				if ((this._BatteryCharging != value))
				{
					this.OnBatteryChargingChanging(value);
					this.SendPropertyChanging();
					this._BatteryCharging = value;
					this.SendPropertyChanged("BatteryCharging");
					this.OnBatteryChargingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jack", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Jack
		{
			get
			{
				return this._Jack;
			}
			set
			{
				if ((this._Jack != value))
				{
					this.OnJackChanging(value);
					this.SendPropertyChanging();
					this._Jack = value;
					this.SendPropertyChanged("Jack");
					this.OnJackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIM", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SIM
		{
			get
			{
				return this._SIM;
			}
			set
			{
				if ((this._SIM != value))
				{
					this.OnSIMChanging(value);
					this.SendPropertyChanging();
					this._SIM = value;
					this.SendPropertyChanged("SIM");
					this.OnSIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkTechnology", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NetworkTechnology
		{
			get
			{
				return this._NetworkTechnology;
			}
			set
			{
				if ((this._NetworkTechnology != value))
				{
					this.OnNetworkTechnologyChanging(value);
					this.SendPropertyChanging();
					this._NetworkTechnology = value;
					this.SendPropertyChanged("NetworkTechnology");
					this.OnNetworkTechnologyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dimensions", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Dimensions
		{
			get
			{
				return this._Dimensions;
			}
			set
			{
				if ((this._Dimensions != value))
				{
					this.OnDimensionsChanging(value);
					this.SendPropertyChanging();
					this._Dimensions = value;
					this.SendPropertyChanged("Dimensions");
					this.OnDimensionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightGm", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string WeightGm
		{
			get
			{
				return this._WeightGm;
			}
			set
			{
				if ((this._WeightGm != value))
				{
					this.OnWeightGmChanging(value);
					this.SendPropertyChanging();
					this._WeightGm = value;
					this.SendPropertyChanged("WeightGm");
					this.OnWeightGmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrderTbl")]
	public partial class OrderTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _ProductName;
		
		private string _BrandName;
		
		private string _Category;
		
		private int _Quantity;
		
		private double _Payment;
		
		private bool _PaymentStatus;
		
		private string _Color;
		
		private string _UserId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnBrandNameChanging(string value);
    partial void OnBrandNameChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnPaymentChanging(double value);
    partial void OnPaymentChanged();
    partial void OnPaymentStatusChanging(bool value);
    partial void OnPaymentStatusChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    #endregion
		
		public OrderTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string BrandName
		{
			get
			{
				return this._BrandName;
			}
			set
			{
				if ((this._BrandName != value))
				{
					this.OnBrandNameChanging(value);
					this.SendPropertyChanging();
					this._BrandName = value;
					this.SendPropertyChanged("BrandName");
					this.OnBrandNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment", DbType="Float NOT NULL")]
		public double Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this.OnPaymentChanging(value);
					this.SendPropertyChanging();
					this._Payment = value;
					this.SendPropertyChanged("Payment");
					this.OnPaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentStatus", DbType="Bit NOT NULL")]
		public bool PaymentStatus
		{
			get
			{
				return this._PaymentStatus;
			}
			set
			{
				if ((this._PaymentStatus != value))
				{
					this.OnPaymentStatusChanging(value);
					this.SendPropertyChanging();
					this._PaymentStatus = value;
					this.SendPropertyChanged("PaymentStatus");
					this.OnPaymentStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(20)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CartTbl")]
	public partial class CartTbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _ProductName;
		
		private string _BrandName;
		
		private string _Category;
		
		private int _Quantity;
		
		private string _Color;
		
		private string _UserId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnBrandNameChanging(string value);
    partial void OnBrandNameChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    #endregion
		
		public CartTbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string BrandName
		{
			get
			{
				return this._BrandName;
			}
			set
			{
				if ((this._BrandName != value))
				{
					this.OnBrandNameChanging(value);
					this.SendPropertyChanging();
					this._BrandName = value;
					this.SendPropertyChanged("BrandName");
					this.OnBrandNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(20)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
